services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models/best_model_al_entropy:/app/models/best_model:ro
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
